services:
  - type: web
    name: nagolie-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nagolie-db
          property: connectionString

  - type: static
    name: nagolie-frontend
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishDirectory: frontend/dist
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
        condition: !static

databases:
  - name: nagolie-db
    plan: free